<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnClose</name>
   <tag></tag>
   <elementGuidId>dd4bd22f-9942-430c-a60e-8b3bb7084bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@title='Close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@title='Close']</value>
      <webElementGuid>424a5acb-5f98-48cf-ab14-d52f69a76f4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
