<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDelete</name>
   <tag></tag>
   <elementGuidId>d7fd057a-b62d-4273-9b8d-2efbd256e562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Delete']</value>
      <webElementGuid>db2b38e0-ff17-44de-8399-e28ae83f2b6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
