<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnYes(Delete)</name>
   <tag></tag>
   <elementGuidId>205d08e6-df24-4ad1-9a32-f11688659b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Yes']</value>
      <webElementGuid>9df7df78-08eb-4ab4-906e-372230f64f11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
