<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>closeFilter</name>
   <tag></tag>
   <elementGuidId>43961da1-666b-4402-9a07-7672b5cec3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//abbr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//abbr</value>
      <webElementGuid>512cdde0-5492-4c0d-9eac-6a4e7bc5ba76</webElementGuid>
   </webElementProperties>
</WebElementEntity>
