<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dataNewDept</name>
   <tag></tag>
   <elementGuidId>1d1177b4-f252-495e-a7a3-41b5bb886d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='${newdept}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='${newdept}']</value>
      <webElementGuid>cc28a476-275d-4544-bb27-c3c77759b24b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
