<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elementSearch</name>
   <tag></tag>
   <elementGuidId>f0fd65ff-2eaa-48ea-9712-c74c837fe977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='${codeclick}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='${codeclick}']</value>
      <webElementGuid>0f4e4941-4d7e-4891-8370-53f7d2b29dd1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
