<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filterData</name>
   <tag></tag>
   <elementGuidId>e789bd82-4816-41d4-ad53-c1e06a18f2a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='s2id_PTI_OSS_Setup_DepartmentGrid0_QuickFilter_Username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='s2id_PTI_OSS_Setup_DepartmentGrid0_QuickFilter_Username']</value>
      <webElementGuid>3cacd2cc-9f65-4085-8bb2-4825d915e0ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
