<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filterData</name>
   <tag></tag>
   <elementGuidId>e65d8568-8bfe-4bbb-884d-4dc4374afd2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='s2id_PTI_OSS_Setup_DepartmentGrid0_QuickFilter_Username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='s2id_PTI_OSS_Setup_DepartmentGrid0_QuickFilter_Username']</value>
      <webElementGuid>64a58900-6abb-4529-baed-f1becafd5ea3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
