<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getText(inputFilter)</name>
   <tag></tag>
   <elementGuidId>57594f52-5333-4bee-a63f-6d57e7b2da95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='select2-chosen-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='select2-chosen-1']</value>
      <webElementGuid>56beb8f9-aab7-4bc5-b294-97ca062365f9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
