<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyHomepage</name>
   <tag></tag>
   <elementGuidId>fc708483-6e08-45cf-aaed-8cac9915461b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[h1='Dashboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[h1='Dashboard']</value>
      <webElementGuid>f062ad1a-63f1-4cc6-aec3-194ef0010d72</webElementGuid>
   </webElementProperties>
</WebElementEntity>
