<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNewData</name>
   <tag></tag>
   <elementGuidId>7f59bf3d-d8e8-4245-a8f4-211de2a3a123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='${newdata}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='${newdata}']</value>
      <webElementGuid>2104b088-7d6e-439b-bcff-bf03bd3ba3b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
