<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_AddProperties</name>
   <tag></tag>
   <elementGuidId>3e42ebc8-8f52-4806-8d60-8f3e6b5a100b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PTI_OSS_Setup_MessageCategoryGroupDialog134_MessageCategoryDetails&quot;]/div[1]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;PTI_OSS_Setup_MessageCategoryGroupDialog134_MessageCategoryDetails&quot;]/div[1]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PTI_OSS_Setup_MessageCategoryGroupDialog134_MessageCategoryDetails&quot;]/div[1]/div/div/div/div/div</value>
      <webElementGuid>4fdaabea-12e9-405c-8853-2b3f1d5fae5a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
