<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Group</name>
   <tag></tag>
   <elementGuidId>b6cbd1cc-7f35-49e4-9cd8-d9627ac77bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PTI_OSS_Setup_MessageCategoryDialog7_MessageCategoryGroups&quot;]/div[1]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
