<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Properties</name>
   <tag></tag>
   <elementGuidId>e2aeb48a-49e3-433e-b0bf-2904e50b179a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PTI_OSS_Setup_MessageCategoryGroupDialog265_MessageCategoryDetails&quot;]/div[2]/div[4]/div[3]/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
