<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textfield_seqno_detail</name>
   <tag></tag>
   <elementGuidId>e450e6e0-ac32-497b-ba02-9aef913fc155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#PTI_OSS_Setup_MessageCategoryDetailDialog48_SeqNo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
