<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuOption</name>
   <tag></tag>
   <elementGuidId>25b71f0e-0751-4da2-a222-6007d7d6e0f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[normalize-space()='${optionsetup}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space()='${optionsetup}']</value>
      <webElementGuid>e097f032-5eb6-4b62-a039-0ce5194cc260</webElementGuid>
   </webElementProperties>
</WebElementEntity>
